packaging_format = 2

id = "encryptor-decryptor"
name = "Encryptor-Decryptor"
description.en = "Encrypts and decrypts any file using PGP"
description.fr = "Chiffre et déchiffre n'importe quel fichier à l'aide de PGP"

version = "2024.07.31~ynh2"

maintainers = []

[upstream]
license = "MIT"
website = "https://prizz.github.io/Easy-File-Encryptor-Decryptor/"
demo = "https://prizz.github.io/Easy-File-Encryptor-Decryptor/"
code = "https://github.com/pRizz/Easy-File-Encryptor-Decryptor"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/encryptor-decryptor"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/pRizz/Easy-File-Encryptor-Decryptor/archive/6040134bb07b1b2016abfb74d38ad092f14e29d1.tar.gz"
        sha256 = "0abc8021403fadfd1fd8cabd7a84bf8e8bc2bfb007fd0fc155e295db1987eb58"
        autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
