packaging_format = 2

id = "encryptor-decryptor"
name = "Encryptor-Decryptor"
description.en = "Encrypts and decrypts any file using PGP"
description.fr = "Chiffre et déchiffre n'importe quel fichier à l'aide de PGP"

version = "1.0~ynh2"

maintainers = []

[upstream]
license = "MIT"
website = "https://prizz.github.io/Easy-File-Encryptor-Decryptor/"
demo = "https://prizz.github.io/Easy-File-Encryptor-Decryptor/"
code = "https://github.com/pRizz/Easy-File-Encryptor-Decryptor"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/encryptor-decryptor"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/pRizz/Easy-File-Encryptor-Decryptor/archive/c8f3fd64e93cc5fdf4336e62f16010ef7ccc3709.zip"
        sha256 = "c91ba3f812e7b2f3657678e627eeaddf071e41a80c88f96438cde2484b5cf0d2"
        autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
