packaging_format = 2

id = "encryptor-decryptor"
name = "Encryptor-Decryptor"
description.en = "Encrypts and decrypts any file using PGP"
description.fr = "Chiffre et déchiffre n'importe quel fichier à l'aide de PGP"

version = "2017.09.03~ynh1"

maintainers = []

[upstream]
license = "MIT"
website = "https://prizz.github.io/Easy-File-Encryptor-Decryptor/"
demo = "https://prizz.github.io/Easy-File-Encryptor-Decryptor/"
code = "https://github.com/pRizz/Easy-File-Encryptor-Decryptor"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/encryptor-decryptor"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/pRizz/Easy-File-Encryptor-Decryptor/archive/c8f3fd64e93cc5fdf4336e62f16010ef7ccc3709.tar.gz"
        sha256 = "1e411399a5598f878282ab719dca72b0653aec5cd4a43310ae304e209968be13"
        autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
