packaging_format = 2

id = "encryptor-decryptor"
name = "Encryptor-Decryptor"
description.en = "Encrypts and decrypts any file using PGP"
description.fr = "Chiffre et déchiffre n'importe quel fichier à l'aide de PGP"

version = "2025.06.19~ynh1"

maintainers = []

[upstream]
license = "MIT"
website = "https://prizz.github.io/Easy-File-Encryptor-Decryptor/"
demo = "https://prizz.github.io/Easy-File-Encryptor-Decryptor/"
code = "https://github.com/pRizz/Easy-File-Encryptor-Decryptor"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/encryptor-decryptor"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/pRizz/Easy-File-Encryptor-Decryptor/archive/238ba2284fb8af29c495e3f5607c28dc5f929002.tar.gz"
        sha256 = "81e8952e9d1d7e35fe6d61f33d8695dcbd6d71e633c45c02373c35263a9b4340"
        autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
